### ISSUE TITLE
Auth token deleted by sls package/deploy

### ISSUE THREAD

**Issue by evaneaston** [marcy-terui/serverless-alexa-skills#1]
Once you run `sls alexa auth` it puts `alexa-skills-token.json` into the `.serverless` directory.  Then if you have a lambda and try to deploy it, the aws provider code runs the [aws:common:cleanupTempDir](https://github.com/serverless/serverless/blob/master/lib/plugins/aws/common/lib/cleanupTempDir.js)  hook which removes the `.serverless` directory and `alexa-skills-token.json` along with it.

To facilitate development, it would be nice to store the token in a different location so it survives lambda (re)deploys.

**Comment by marcy-terui** [comment]
Thank you for your suggestion.

> To facilitate development, it would be nice to store the token in a different location so it survives lambda (re)deploys.

I think so too. I would like to think about a location to save the tokens. Do you have any ideas? @Evaneaston

**Comment by marcy-terui** [comment]
Fixed by #2

**Comment by evaneaston** [comment]
I don't have any suggestions.  Putting it in a dot file like you did seems fine.  If you ended up needing to manage more files a new dot directory would make sense.
