### ISSUE TITLE
Use default vendor when only one available for user

### ISSUE THREAD

**Issue by danielrbradley** [marcy-terui/serverless-alexa-skills#15]
- The user's available vendor ids can be listed through the API at `GET https://api.amazonalexa.com/v1/vendors` with the OAuth token in the `Authorization` header.
- If no vendor ID has been specified, and only 1 vendor is listed on the API, we should use that vendor by default.

This will reduce setup friction for new users setting up their first skill.

**Comment by marcy-terui** [comment]
> https://api.amazonalexa.com/v1/vendors with the OAuth token in the Authorization header.

I didn't know this API. I think it is a very nice idea !
