### ISSUE TITLE
Option for Launch Request

### ISSUE THREAD

**Issue by danquack** [marcy-terui/serverless-alexa-skills#19]
I can’t find any info in the readme or through users examples, but I’m looking to add a launch request. Can you provide an example of how to do so?

**Comment by danielrbradley** [comment]
There's no configuration you have to add for launch requests - you just need to add a handler in your code. All custom skills will automatically trigger a launch request if the user invokes the skill without an intent. E.g. https://github.com/danielrbradley/alexa-typescript-demo/blob/master/handler.ts#L118-L124

**Comment by danquack** [comment]
@danielrbradley ah thanks.
